Repository dispatchrun/dispatch-py, pull requests merged in 2024-03, with the labels that each got.

#97 rename dispatch-sdk-protobuf to dispatch-proto
  Makefile
  README.md
  buf.work.yaml
Labels: enhancement

#98 rename from dispatch-sdk-python to dispatch-py
  .github/workflows/pypi.yml
  README.md
  docs/index.md
  examples/getting_started/app.py
  pyproject.toml
Labels: documentation, enhancement

#83 doc: add example using gather
  examples/fanout/__init__.py
  examples/fanout/fanout.py
  examples/fanout/test_fanout.py
  examples/github_stats/app.py
Labels: documentation

#100 Improve type safety with ParamSpec
  src/buf/validate/py.typed
  src/dispatch/experimental/durable/py.typed
  src/dispatch/function.py
  src/dispatch/integrations/py.typed
  src/dispatch/py.typed
  src/dispatch/sdk/v1/py.typed
  tests/dispatch/test_function.py
  tests/test_fastapi.py
Labels: enhancement, breaking change

#101 Improve type checking of call results
  src/dispatch/function.py
Labels: enhancement, breaking change

#114 remove httpx dependency from dispatch.fastapi module
  src/dispatch/fastapi.py
Labels: bug

#118 Add section describing serialization and its quirks
  README.md
  src/dispatch/experimental/durable/function.py
Labels: documentation

#139 v0.4.1: fix build
  setup.py
Labels: bug

#141 Add MANIFEST.in
  MANIFEST.in
Labels: bug
