Repository dispatchrun/dispatch-py, pull requests merged in 2024-02, with the labels that each got.

#72 propagate exception traceback
  pyproject.toml
  src/dispatch/proto.py
  src/dispatch/scheduler.py
  src/dispatch/status.py
  tests/dispatch/test_error.py
  tests/dispatch/test_status.py
Labels: bug

#77 FastAPI: return error responses formatted for the connectrpc protocol
  src/dispatch/fastapi.py
  src/dispatch/signature/digest.py
  tests/dispatch/signature/test_signature.py
  tests/test_full.py
Labels: bug

#79 Remove coroutine decorator
  README.md
  examples/auto_retry/app.py
  examples/getting_started/app.py
  src/dispatch/experimental/durable/function.py
  src/dispatch/function.py
  src/dispatch/scheduler.py
  tests/test_full.py
Labels: enhancement

#81 fix coroutine decoration
  src/dispatch/function.py
Labels: bug

#82 don't crash on missing error traceback
  src/dispatch/proto.py
  tests/dispatch/test_error.py
Labels: bug

#78 doc: add github stats example
  examples/github_stats/__init__.py
  examples/github_stats/app.py
  examples/github_stats/test_app.py
Labels: documentation
